resolver: lts-14.4
packages:
  - serversession
  - serversession-backend-acid-state
  - serversession-backend-persistent
  - serversession-backend-redis
  - serversession-frontend-snap
  - serversession-frontend-wai
  - serversession-frontend-yesod
  - examples/serversession-example-yesod-persistent
flags:
  serversession:
    lib-Werror: true
  serversession-backend-acid-state:
    lib-Werror: true
  serversession-backend-persistent:
    lib-Werror: true
  serversession-backend-redis:
    lib-Werror: true
  serversession-frontend-snap:
    lib-Werror: true
  serversession-frontend-wai:
    lib-Werror: true
  serversession-frontend-yesod:
    lib-Werror: true
extra-deps:
  - acid-state-0.14.3
  - snap-1.1.1.0
  - heist-1.1
  - map-syntax-0.3
  - pwstore-fast-2.4.4
  - xmlhtml-0.2.5.2
